export const ALLOWED_FILTER_SORT_FIELDS = [
  'id',
  'lastName',
  'middleName',
  'firstName',
  'dateOfBirth',
  'age',
  'din',
  'csaStatus',
  'csaStatusEffectiveDate',
  'legacyFileNumber',
  'lastUpdatedAt',
  'lastUpdatedBy',
  'caseNumber',
  'caseType',
  'caseStatus',
  'gender',
  'serviceOffice',
  'assignedTo',
] as const
