export const CRA_DATA_HANDLING_CONSTANT = {
  FILE_NAME_PREFIX: 'HT',
  REQUEST_FILE: {
    HEADER_TRAN_CODE: 6133,
    DETAIL_TRAN_CODE: 6134,
    TRAILER_TRAN_CODE: 6135,
    HEADER_RECORD_CONT: '00000000',
    VERSION_NUM: 'V00.0',
    BUSINESS_NUM: '885633354RA0001',
  },
  RESPONSE_FILE: {},
  FILE_TRANSFER_STATUS: {
    COMPLETED: 'COMPLETED',
    PENDING: 'PENDING',
  },
  CRA_USERID: 'craUserId',
  DESTINATION_ID: 'cra-ftp',
}
