export const CRA_DATA_HANDLING_CONSTANT = {
  FILE_CREATION_ENVIROMENT: process.env.NODE_ENV === 'production' ? 'PCSAIN' : 'ACSAIN',
  FILE_TYPE_APPLICATION: process.env.NODE_ENV === 'production' ? 'PAPL' : 'AAPL',
  FILE_NAME_PREFIX: 'HT',
  FILE_TRANSACTION_CODE: {
    HEADER_TRAN_CODE: 6133,
    DETAIL_TRAN_CODE: 6134,
    TRAILER_TRAN_CODE: 6135,
  },
}
