-- ============================================================
-- CSA Status + DIN One-Time Remediation
-- ============================================================
-- Ticket:      <ticket-number>
-- Date:        <yyyy-mm-dd>
-- Author:      <name>
-- Environment: <Pre-Prod | Prod>
-- Source CSV:  <SharePoint link>
--
-- Purpose:
--   Update csa_status and din on contacts that have incorrect
--   values in the CSA app, then flag them for ICM sync-back.
--
-- MIS → CSA status mapping:
--   IM  →  In Pay
--   OM  →  Not Eligible - Out of Pay
--   AS  →  Batch Sent - Application
--   CS  →  Batch Sent - Cancellation
--
-- Matching key: legacy_file_number (one contact per file number
--   confirmed by duplicate check in Step 1)
--
-- Fields updated: csa_status, din, icm_integration_status
--   icm_integration_status is set to TRUE so SYNC_ICM picks
--   up these records and pushes the changes back to ICM.
--
-- Steps:
--   1. Duplicate check   — confirm no file number maps to >1 contact
--   2. Pre-check         — confirm all file numbers are found (no NULLs)
--   3. UPDATE            — apply remediation inside a transaction
--   4. Post-check        — verify values landed correctly
--   5. Trigger SYNC_ICM  — POST /jobs/sync-icm (or node entrypoint)
--
-- DO NOT run Steps 3-5 if Steps 1-2 show unexpected results.
-- How to populate the VALUES block from the source CSV:
--   In Excel/Sheets, add a helper column with this formula:
--   =("('"&A2&"', '"&B2&"', '"&C2&"'),")
--   where A = Legacy File Num, B = CSA Status (MIS code), C = DIN.
--   Copy the column down for all rows, paste the result into the
--   VALUES blocks in Steps 2 and 3 below.
-- ============================================================


-- ============================================================
-- STEP 1: Duplicate check
-- Expected: zero rows returned.
-- Any row returned means a file number maps to >1 contact.
-- Investigate before proceeding.
-- ============================================================

SELECT legacy_file_number, COUNT(*) AS contact_count
FROM csa.contacts
WHERE legacy_file_number IN (
  -- paste all legacy file numbers from the extract here
  -- e.g. '12345', '67890'
)
GROUP BY legacy_file_number
HAVING COUNT(*) > 1;


-- ============================================================
-- STEP 2: Pre-check (read-only, no changes)
-- Expected: every row has a non-NULL c.id.
-- Rows with NULL c.id = file number not found in CSA app.
-- Resolve all NULLs before running the UPDATE.
-- ============================================================

SELECT
  r.legacy_file_num,
  r.mis_status,
  r.din             AS incoming_din,
  c.id,
  c.csa_status      AS current_csa_status,
  c.din             AS current_din
FROM (VALUES
  -- generated by generate-remediation-sql.py — do not edit manually
  -- ('legacy_file_num', 'mis_status', 'din'),
  ('PLACEHOLDER', 'IM', 'DIN-PLACEHOLDER')
) AS r(legacy_file_num, mis_status, din)
LEFT JOIN csa.contacts c ON c.legacy_file_number = r.legacy_file_num
ORDER BY c.id;


-- ============================================================
-- STEP 3: Remediation UPDATE
-- Review Steps 1 and 2 before running this block.
-- Check the row count after UPDATE matches expected (~1000).
-- ROLLBACK if anything looks wrong; COMMIT when confirmed.
-- ============================================================

BEGIN;

WITH remediation_data AS (
  SELECT * FROM (VALUES
    -- generated by generate-remediation-sql.py — do not edit manually
    -- ('legacy_file_num', 'mis_status', 'din'),
    ('PLACEHOLDER', 'IM', 'DIN-PLACEHOLDER')
  ) AS t(legacy_file_num, mis_status, din)
),
mapped AS (
  SELECT
    legacy_file_num,
    CASE mis_status
      WHEN 'IM' THEN 'In Pay'
      WHEN 'OM' THEN 'Not Eligible - Out of Pay'
      WHEN 'AS' THEN 'Batch Sent - Application'
      WHEN 'CS' THEN 'Batch Sent - Cancellation'
    END AS csa_status,
    din
  FROM remediation_data
)
UPDATE csa.contacts c
SET
  csa_status             = m.csa_status,
  din                    = m.din,
  icm_integration_status = true   -- flags record for SYNC_ICM pickup
FROM mapped m
WHERE c.legacy_file_number = m.legacy_file_num;

-- Verify row count matches Step 2 result before committing
-- ROLLBACK;
COMMIT;


-- ============================================================
-- STEP 4: Post-check
-- Confirm updated values are correct.
-- Row count must match the UPDATE result from Step 3.
-- ============================================================

SELECT
  c.id,
  c.legacy_file_number,
  c.csa_status,
  c.din,
  c.icm_integration_status
FROM csa.contacts c
WHERE c.legacy_file_number IN (
  -- paste all legacy file numbers from the extract here
)
ORDER BY c.id;


-- ============================================================
-- STEP 5: Trigger ICM sync-back (run after COMMIT)
-- POST /jobs/sync-icm
-- or: node dist/jobs/entrypoints/sync-icm.js  (on the pod)
--
-- The job will pick up all contacts with icm_integration_status=TRUE
-- and push csa_status + din back to ICM.
-- ============================================================
