-- ============================================================
-- CSA Status + DIN One-Time Remediation
-- ============================================================
-- Ticket:      <ticket-number>
-- Date:        <yyyy-mm-dd>
-- Author:      <name>
-- Environment: <Pre-Prod | Prod>
-- Source file: <SharePoint link>
-- Total rows:  <n>
-- Rows with empty DIN in source: <n>
--
-- Purpose:
--   Update csa_status and din on contacts that have incorrect
--   values in the CSA app, then flag them for ICM sync-back.
--
-- CSA status DB constants:
--   in_pay                    →  In Pay
--   not_eligible_out_of_pay   →  Not Eligible - Out of Pay
--   eligible_tbd              →  Eligible - TBD
--   eligible                  →  Eligible
--   on_hold                   →  On Hold
--   in_batch_application      →  In Batch - Application
--   batch_sent_application    →  Batch Sent - Application
--   application_refused_cra   →  Application Refused - CRA
--   not_eligible_in_pay       →  Not Eligible - In Pay
--   not_eligible_ip_tbd       →  Not Eligible - IP - TBD
--   in_batch_cancellation     →  In Batch - Cancellation
--   batch_sent_cancellation   →  Batch Sent - Cancellation
--   cancellation_refused_cra  →  Cancellation Refused - CRA
--   cra_error_application     →  CRA Error - Application
--   cra_error_cancellation    →  CRA Error - Cancellation
--   over_18                   →  Over 18
--
-- Matching key: case_number (one contact per case number,
--   confirmed by duplicate check in Step 1)
--
-- Fields updated: csa_status, din, icm_integration_status
--   icm_integration_status is set to TRUE so SYNC_ICM picks
--   up these records and pushes the changes back to ICM.
--
-- Steps:
--   1. Duplicate check   — confirm no case number maps to >1 contact
--   2. Pre-check         — confirm all case numbers are found (no NULLs)
--   3. UPDATE            — apply remediation inside a transaction
--   4. Post-check        — verify values landed correctly
--   5. Trigger SYNC_ICM  — POST /jobs/sync-icm (or node entrypoint)
--
-- DO NOT run Steps 3-5 if Steps 1-2 show unexpected results.
--
-- How to populate the VALUES blocks:
--   Run generate-remediation-sql.py against the source Excel file.
--   DO NOT edit the generated VALUES blocks manually.
-- ============================================================


-- ============================================================
-- STEP 1: Duplicate check
-- Expected: zero rows returned.
-- Any row returned means a case number maps to >1 contact.
-- Investigate before proceeding.
-- ============================================================

SELECT case_number, COUNT(*) AS contact_count
FROM csa.contacts
WHERE case_number IN (
  -- paste all case numbers from the extract here
  -- e.g. '1-12345678', '1-67890123'
)
GROUP BY case_number
HAVING COUNT(*) > 1;


-- ============================================================
-- STEP 2: Pre-check (read-only, no changes)
-- Expected: every row has a non-NULL c.id.
-- Rows with NULL c.id = case number not found in CSA app.
-- Resolve all NULLs before running the UPDATE.
-- ============================================================

SELECT
  r.case_num,
  r.csa_status,
  r.din             AS incoming_din,
  c.id,
  c.csa_status      AS current_csa_status,
  c.din             AS current_din
FROM (VALUES
  -- generated by generate-remediation-sql.py — do not edit manually
  -- ('case_num', 'csa_status_db_constant', 'din'),
  ('PLACEHOLDER', 'in_pay', 'DIN-PLACEHOLDER')
) AS r(case_num, csa_status, din)
LEFT JOIN csa.contacts c ON c.case_number = r.case_num
ORDER BY c.id;


-- ============================================================
-- STEP 3: Remediation UPDATE
-- Review Steps 1 and 2 before running this block.
-- Check the row count after UPDATE matches expected.
-- ROLLBACK if anything looks wrong; COMMIT when confirmed.
-- ============================================================

BEGIN;

WITH remediation_data AS (
  SELECT * FROM (VALUES
    -- generated by generate-remediation-sql.py — do not edit manually
    -- ('case_num', 'csa_status_db_constant', 'din'),
    ('PLACEHOLDER', 'in_pay', 'DIN-PLACEHOLDER')
  ) AS t(case_num, csa_status, din)
)
UPDATE csa.contacts c
SET
  csa_status             = r.csa_status,
  din                    = r.din,
  icm_integration_status = true   -- flags record for SYNC_ICM pickup
FROM remediation_data r
WHERE c.case_number = r.case_num;

-- Verify row count matches Step 2 result before committing
-- ROLLBACK;
COMMIT;


-- ============================================================
-- STEP 4: Post-check
-- Confirm updated values are correct.
-- Row count must match the UPDATE result from Step 3.
-- ============================================================

SELECT
  c.id,
  c.case_number,
  c.csa_status,
  c.din,
  c.icm_integration_status
FROM csa.contacts c
WHERE c.case_number IN (
  -- paste all case numbers from the extract here
)
ORDER BY c.id;


-- ============================================================
-- STEP 5: Trigger ICM sync-back (run after COMMIT)
-- POST /jobs/sync-icm
-- or: node dist/jobs/entrypoints/sync-icm.js  (on the pod)
--
-- The job will pick up all contacts with icm_integration_status=TRUE
-- and push csa_status + din back to ICM.
-- ============================================================
