#!/usr/bin/env python3
"""
generate-remediation-sql.py
============================
Reads a remediation Excel extract and writes a ready-to-run SQL file.

Expected Excel columns (0-based index):
  0  Case Number               → case_number  (matching key in csa.contacts)
  1  Legacy File ID            → for reference only
  2  Last Name                 → for reference only
  3  First Name                → for reference only
  4  DIN                       → din
  5  CSA Status - Current State → for reference only
  6  Target CSA Status         → csa_status target value (human-readable label)

Rows where the target status is blank / None are skipped.
Common capitalisation typos (e.g. 'IN Pay') are normalised automatically.

Usage:
    pip install openpyxl
    python3 generate-remediation-sql.py <excel_file> <output_sql>

Example:
    python3 generate-remediation-sql.py remediation.xlsx remediation.sql
"""

import os
import sys
from datetime import datetime

import openpyxl

STATUS_LABEL_TO_DB: dict[str, str] = {
    "In Pay":                        "in_pay",
    "Not Eligible - Out of Pay":     "not_eligible_out_of_pay",
    "Eligible - TBD":                "eligible_tbd",
    "Eligible TBD":                  "eligible_tbd",
    "Eligible":                      "eligible",
    "On Hold":                       "on_hold",
    "In Batch - Application":        "in_batch_application",
    "Batch Sent - Application":      "batch_sent_application",
    "Application Refused - CRA":     "application_refused_cra",
    "Not Eligible - In Pay":         "not_eligible_in_pay",
    "Not Eligible - IP - TBD":       "not_eligible_ip_tbd",
    "In Batch - Cancellation":       "in_batch_cancellation",
    "Batch Sent - Cancellation":     "batch_sent_cancellation",
    "Cancellation Refused - CRA":    "cancellation_refused_cra",
    "CRA Error - Application":       "cra_error_application",
    "CRA Error - Cancellation":      "cra_error_cancellation",
    "Over 18":                       "over_18",
}

SKIP_LABELS = {"blank", "none", ""}


def normalise_label(raw: str) -> str:
    """Normalise capitalisation variants before mapping."""
    s = raw.strip()
    # case-insensitive match for 'in pay' handles 'IN Pay', 'in pay', etc.
    if s.lower() == "in pay":
        return "In Pay"
    return s


def label_to_db(label: str) -> str:
    key = normalise_label(label)
    if key not in STATUS_LABEL_TO_DB:
        raise ValueError(f"Unknown CSA status label: '{key}' — add it to STATUS_LABEL_TO_DB")
    return STATUS_LABEL_TO_DB[key]


def load_rows(path: str) -> tuple[list[tuple[str, str, str]], int, int]:
    """
    Return (rows, skipped_count, empty_din_count).
    rows: list of (case_number, csa_status_db, din_str)
    """
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb.active
    rows: list[tuple[str, str, str]] = []
    skipped = 0
    empty_din = 0

    for row in ws.iter_rows(min_row=2, values_only=True):
        case_num = row[0]
        if not case_num:
            continue

        raw_target = str(row[6]).strip() if row[6] is not None else ""
        if raw_target.lower() in SKIP_LABELS:
            skipped += 1
            continue

        din = row[4]
        if din is None or str(din).strip() == "":
            din_str = ""
            empty_din += 1
        else:
            din_str = str(int(din)) if isinstance(din, float) else str(din).strip()

        status_db = label_to_db(raw_target)
        rows.append((str(case_num).strip(), status_db, din_str))

    return rows, skipped, empty_din


def in_list(rows: list[tuple]) -> str:
    return "\n".join(
        f"  '{r[0]}'" + ("," if i < len(rows) - 1 else "")
        for i, r in enumerate(rows)
    )


def values_list(rows: list[tuple]) -> str:
    return "\n".join(
        f"  ('{r[0]}', '{r[1]}', '{r[2]}')" + ("," if i < len(rows) - 1 else "")
        for i, r in enumerate(rows)
    )


def build_sql(rows: list[tuple], source_file: str, skipped: int, empty_din: int) -> str:
    today     = datetime.today().strftime("%Y-%m-%d")
    count     = len(rows)
    in_block  = in_list(rows)
    val_block = values_list(rows)

    return f"""\
-- ============================================================
-- CSA Status + DIN One-Time Remediation
-- ============================================================
-- Date:        {today}
-- Source:      {os.path.basename(source_file)}
-- Total rows:  {count}
-- Skipped rows (blank target status): {skipped}
-- Rows with empty DIN in source (din will be set to empty): {empty_din}
-- Matching key: case_number (required, NOT NULL on csa.contacts)
--
-- Generated by: generate-remediation-sql.py
-- DO NOT edit the VALUES blocks manually — re-run the script instead.
-- ============================================================


-- ============================================================
-- STEP 1: Duplicate check
-- Expected: zero rows. Investigate any row returned.
-- ============================================================

SELECT case_number, COUNT(*) AS contact_count
FROM csa.contacts
WHERE case_number IN (
{in_block}
)
GROUP BY case_number
HAVING COUNT(*) > 1;


-- ============================================================
-- STEP 2: Pre-check (read-only)
-- Expected: every row has a non-NULL c.id.
-- Rows with NULL c.id = case number not found - resolve before UPDATE.
-- ============================================================

SELECT
  r.case_num,
  r.csa_status,
  r.din             AS incoming_din,
  c.id,
  c.csa_status      AS current_csa_status,
  c.din             AS current_din
FROM (VALUES
{val_block}
) AS r(case_num, csa_status, din)
LEFT JOIN csa.contacts c ON c.case_number = r.case_num
ORDER BY c.id;


-- ============================================================
-- STEP 3: Remediation UPDATE
-- Review Steps 1 and 2 before running this block.
-- ROLLBACK if anything looks wrong; COMMIT when confirmed.
-- ============================================================

BEGIN;

WITH remediation_data AS (
  SELECT * FROM (VALUES
{val_block}
  ) AS t(case_num, csa_status, din)
)
UPDATE csa.contacts c
SET
  csa_status             = r.csa_status,
  din                    = r.din,
  icm_integration_status = true
FROM remediation_data r
WHERE c.case_number = r.case_num;

-- Verify row count matches Step 2 result before committing (~{count} expected)
-- ROLLBACK;
COMMIT;


-- ============================================================
-- STEP 4: Post-check
-- ============================================================

SELECT
  c.id,
  c.case_number,
  c.csa_status,
  c.din,
  c.icm_integration_status
FROM csa.contacts c
WHERE c.case_number IN (
{in_block}
)
ORDER BY c.id;


-- ============================================================
-- STEP 5: Trigger ICM sync-back (run after COMMIT)
-- POST /jobs/sync-icm
-- or: node dist/jobs/entrypoints/sync-icm.js  (on the pod)
-- ============================================================
"""


def main() -> None:
    if len(sys.argv) != 3:
        print("Usage: python3 generate-remediation-sql.py <excel_file> <output_sql>")
        print("Example: python3 generate-remediation-sql.py remediation.xlsx remediation.sql")
        sys.exit(1)

    excel_file  = sys.argv[1]
    output_file = sys.argv[2]

    if not os.path.exists(excel_file):
        print(f"Error: file not found: {excel_file}")
        sys.exit(1)

    print(f"Reading: {excel_file}")
    rows, skipped, empty_din = load_rows(excel_file)
    print(f"Loaded {len(rows)} rows  |  skipped {skipped} (blank target)  |  {empty_din} rows with empty DIN")

    sql = build_sql(rows, excel_file, skipped, empty_din)

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(sql)

    print(f"Written: {output_file}")


if __name__ == "__main__":
    main()
