export enum JobType {
  INGEST_DATA = 'INGEST_DATA',
  INGEST_ICM = 'INGEST_ICM',
  INGEST_MIS = 'INGEST_MIS',
  RUN_ELIGIBILITY = 'RUN_ELIGIBILITY',
  SYNC_ICM = 'SYNC_ICM',
  SEND_CRA_FILE = 'SEND_CRA_FILE',
  POLL_CRA_RESPONSE = 'POLL_CRA_RESPONSE',
  RETRY_FAILED = 'RETRY_FAILED',
}
