export enum JobActivityType {
  STARTED = 'STARTED',
  RECORD_PROCESSED = 'RECORD_PROCESSED',
  BATCH_CREATED = 'BATCH_CREATED',
  FILE_SENT = 'FILE_SENT',
  FILE_RECEIVED = 'FILE_RECEIVED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  WARNING = 'WARNING',
}
