-- ICM staging tables
ALTER TABLE csa.stg_icm_cases ALTER COLUMN INGESTED_AT SET DATA TYPE TIMESTAMPTZ;
ALTER TABLE csa.stg_icm_placements ALTER COLUMN INGESTED_AT SET DATA TYPE TIMESTAMPTZ;
ALTER TABLE csa.stg_icm_legal_authority_admin ALTER COLUMN INGESTED_AT SET DATA TYPE TIMESTAMPTZ;
ALTER TABLE csa.stg_icm_legal_authority ALTER COLUMN INGESTED_AT SET DATA TYPE TIMESTAMPTZ;
ALTER TABLE csa.stg_icm_agreement ALTER COLUMN INGESTED_AT SET DATA TYPE TIMESTAMPTZ;
ALTER TABLE csa.stg_icm_orders ALTER COLUMN INGESTED_AT SET DATA TYPE TIMESTAMPTZ;

-- MIS staging tables
ALTER TABLE csa.stg_mis_payments ALTER COLUMN ingested_at SET DATA TYPE TIMESTAMPTZ;
ALTER TABLE csa.stg_mis_contracts ALTER COLUMN ingested_at SET DATA TYPE TIMESTAMPTZ;
ALTER TABLE csa.stg_mis_placements ALTER COLUMN ingested_at SET DATA TYPE TIMESTAMPTZ;
