import { CSA_EVENT, CSA_STATUS } from '../constants'
import {
  canTransition,
  getNextState,
  getValidEvents,
  type TransitionMap,
  type TransitionTarget,
} from './machine.utils'

// { [fromState]: { [event]: toState | toState[] } }
export const CSA_TRANSITIONS: TransitionMap = {
  [CSA_STATUS.ELIGIBLE]: {
    [CSA_EVENT.ADD_TO_BATCH]: CSA_STATUS.IN_BATCH_APPLICATION,
    [CSA_EVENT.SET_NOT_ELIGIBLE]: CSA_STATUS.NOT_ELIGIBLE_OUT_OF_PAY,
    [CSA_EVENT.AGE_OUT]: CSA_STATUS.OVER_18,
    [CSA_EVENT.HOLD]: CSA_STATUS.ON_HOLD,
  },
  [CSA_STATUS.ELIGIBLE_TBD]: {
    [CSA_EVENT.ADD_TO_BATCH]: CSA_STATUS.IN_BATCH_APPLICATION,
    [CSA_EVENT.AGE_OUT]: CSA_STATUS.OVER_18,
    [CSA_EVENT.SET_NOT_ELIGIBLE]: CSA_STATUS.NOT_ELIGIBLE_OUT_OF_PAY,
    [CSA_EVENT.BECOME_ELIGIBLE]: CSA_STATUS.ELIGIBLE,
    [CSA_EVENT.HOLD]: CSA_STATUS.ON_HOLD,
  },
  [CSA_STATUS.NOT_ELIGIBLE_OUT_OF_PAY]: {
    [CSA_EVENT.BECOME_ELIGIBLE]: CSA_STATUS.ELIGIBLE,
    [CSA_EVENT.SET_ELIGIBLE_TBD]: CSA_STATUS.ELIGIBLE_TBD,
    [CSA_EVENT.AGE_OUT]: CSA_STATUS.OVER_18,
  },
  [CSA_STATUS.ON_HOLD]: {
    [CSA_EVENT.SET_NOT_ELIGIBLE]: CSA_STATUS.NOT_ELIGIBLE_OUT_OF_PAY,
    [CSA_EVENT.RESUME]: [
      CSA_STATUS.ELIGIBLE,
      CSA_STATUS.ELIGIBLE_TBD,
      CSA_STATUS.APPLICATION_REFUSED_CRA,
      CSA_STATUS.NOT_ELIGIBLE_IN_PAY,
      CSA_STATUS.NOT_ELIGIBLE_IP_TBD,
      CSA_STATUS.CANCELLATION_REFUSED_CRA,
      CSA_STATUS.CRA_ERROR_APPLICATION,
      CSA_STATUS.CRA_ERROR_CANCELLATION,
    ],
  },
  [CSA_STATUS.IN_BATCH_APPLICATION]: {
    [CSA_EVENT.SEND_TO_CRA]: CSA_STATUS.BATCH_SENT_APPLICATION,
    [CSA_EVENT.REMOVE_FROM_BATCH]: [
      CSA_STATUS.ELIGIBLE_TBD,
      CSA_STATUS.APPLICATION_REFUSED_CRA,
      CSA_STATUS.CRA_ERROR_APPLICATION,
    ],
  },
  [CSA_STATUS.BATCH_SENT_APPLICATION]: {
    [CSA_EVENT.CRA_RSP_REJECTED]: CSA_STATUS.CRA_ERROR_APPLICATION,
    [CSA_EVENT.CRA_FILE_REJECTED]: [CSA_STATUS.ELIGIBLE, CSA_STATUS.ELIGIBLE_TBD],
    [CSA_EVENT.CRA_WKL_APPROVED]: CSA_STATUS.IN_PAY,
    [CSA_EVENT.CRA_WKL_REFUSED]: CSA_STATUS.APPLICATION_REFUSED_CRA,
  },
  [CSA_STATUS.APPLICATION_REFUSED_CRA]: {
    [CSA_EVENT.HOLD]: CSA_STATUS.ON_HOLD,
    [CSA_EVENT.ADD_TO_BATCH]: CSA_STATUS.IN_BATCH_APPLICATION,
  },
  [CSA_STATUS.IN_PAY]: {
    [CSA_EVENT.LOSE_PAY_ELIGIBILITY]: CSA_STATUS.NOT_ELIGIBLE_IN_PAY,
    [CSA_EVENT.AGE_OUT]: CSA_STATUS.OVER_18,
    [CSA_EVENT.SET_NOT_ELIGIBLE]: CSA_STATUS.NOT_ELIGIBLE_IP_TBD,
  },
  [CSA_STATUS.NOT_ELIGIBLE_IN_PAY]: {
    [CSA_EVENT.ADD_TO_BATCH]: CSA_STATUS.IN_BATCH_CANCELLATION,
    [CSA_EVENT.BECOME_ELIGIBLE]: CSA_STATUS.IN_PAY,
    [CSA_EVENT.AGE_OUT]: CSA_STATUS.OVER_18,
    [CSA_EVENT.HOLD]: CSA_STATUS.ON_HOLD,
  },
  [CSA_STATUS.NOT_ELIGIBLE_IP_TBD]: {
    [CSA_EVENT.BECOME_ELIGIBLE]: CSA_STATUS.IN_PAY,
    [CSA_EVENT.LOSE_PAY_ELIGIBILITY]: CSA_STATUS.NOT_ELIGIBLE_IN_PAY,
    [CSA_EVENT.AGE_OUT]: CSA_STATUS.OVER_18,
    [CSA_EVENT.ADD_TO_BATCH]: CSA_STATUS.IN_BATCH_CANCELLATION,
    [CSA_EVENT.HOLD]: CSA_STATUS.ON_HOLD,
  },
  [CSA_STATUS.IN_BATCH_CANCELLATION]: {
    [CSA_EVENT.SEND_TO_CRA]: CSA_STATUS.BATCH_SENT_CANCELLATION,
    [CSA_EVENT.REMOVE_FROM_BATCH]: [
      CSA_STATUS.NOT_ELIGIBLE_IP_TBD,
      CSA_STATUS.CANCELLATION_REFUSED_CRA,
      CSA_STATUS.CRA_ERROR_CANCELLATION,
    ],
  },
  [CSA_STATUS.BATCH_SENT_CANCELLATION]: {
    [CSA_EVENT.CRA_RSP_REJECTED]: CSA_STATUS.CRA_ERROR_CANCELLATION,
    [CSA_EVENT.CRA_FILE_REJECTED]: [CSA_STATUS.NOT_ELIGIBLE_IN_PAY, CSA_STATUS.NOT_ELIGIBLE_IP_TBD],
    [CSA_EVENT.CRA_WKL_APPROVED]: CSA_STATUS.NOT_ELIGIBLE_OUT_OF_PAY,
    [CSA_EVENT.CRA_WKL_REFUSED]: CSA_STATUS.CANCELLATION_REFUSED_CRA,
  },
  [CSA_STATUS.CANCELLATION_REFUSED_CRA]: {
    [CSA_EVENT.HOLD]: CSA_STATUS.ON_HOLD,
    [CSA_EVENT.ADD_TO_BATCH]: CSA_STATUS.IN_BATCH_CANCELLATION,
  },
  [CSA_STATUS.CRA_ERROR_APPLICATION]: {
    [CSA_EVENT.HOLD]: CSA_STATUS.ON_HOLD,
    [CSA_EVENT.ADD_TO_BATCH]: CSA_STATUS.IN_BATCH_APPLICATION,
  },
  [CSA_STATUS.CRA_ERROR_CANCELLATION]: {
    [CSA_EVENT.HOLD]: CSA_STATUS.ON_HOLD,
    [CSA_EVENT.ADD_TO_BATCH]: CSA_STATUS.IN_BATCH_CANCELLATION,
  },
  [CSA_STATUS.OVER_18]: {},
}

export const getNextCsaState = (currentState: string, event: string): TransitionTarget =>
  getNextState(CSA_TRANSITIONS, currentState, event)

export const canTransitionCsa = (currentState: string, event: string): boolean =>
  canTransition(CSA_TRANSITIONS, currentState, event)

export const getValidCsaEvents = (currentState: string): string[] =>
  getValidEvents(CSA_TRANSITIONS, currentState)
